#!/bin/sh
set -e

for ENTRY in                   \
    PsychEmitter\$1            \
    PsychEmitter               \
    PsychLibrary\$1            \
    PsychLibrary\$YAMLEncoding \
    PsychLibrary               \
    PsychParser\$1             \
    PsychParser                \
    PsychToRuby\$ClassLoader   \
    PsychToRuby\$ToRuby        \
    PsychToRuby                \
    PsychYamlTree              \
; do
    echo -n "-C tmp/java/psych org/jruby/ext/psych/${ENTRY}.class "
done
