#!/bin/sh
set -e

JAVA_HOME="/usr/lib/jvm/java-8-openjdk-`dpkg-architecture --query DEB_HOST_ARCH`"

for JAR in resources.jar rt.jar sunrsasign.jar jsse.jar jce.jar charsets.jar jfr.jar; do
    echo -n "${JAVA_HOME}/jre/lib/${JAR}:"
done

echo -n "${JAVA_HOME}/jre/classes:"
echo -n "${PWD}/lib/jruby.jar:"
echo -n /usr/share/maven-repo/org/yaml/snakeyaml/1.x/snakeyaml-1.x.jar
